language: node_js
node_js:
- '7'
notifications:
  slack:
    secure: lnIAuBFtI/RDfId8K3+j6VE67OvpEYSr8roINZ3ApS5xqNgh9nHxhgVsuWVmFL4udojwiQdLSKhNwymg+9oapemdZTWOfxeTabOvvefJlC2KECe1ZAUynI71ndtwLcWitFD/BncG3cTwu48POMrREgg0WO4CJQvmFfkGgXqsj3xbs/PldgBIb8Im72U/+sr1//9dZXj/el6flbMRn1yiTeV5sIPkDLvnnBcuQdWlycS1EF8/H3faYgYcwUeFN6x/WieF2bvM75MZq8+cxxIUwGdvGOsoRQYjq//ZBTqu4PdKg/Wp8ui4THYwk9eH4UHCRVhldvtsTVdhg96ApXC5Y8fFEMZFX7hms61PtM51MGUgIpLLZKeok1dtVuT1fkkMNScDUTSHfVBzjJkGDJrP1THHFnvgka1o0qH+t9xR5hBexbW9dTf+uTZw2Yre3IFp8IRUIn5YIcVw0czHpMd5UtY/kJtyfoHN5wQVz13ogy/3gtdzSL1NBaxpj/fMc5iZNdS4ksqsetEcmlmCKcTahDAE8ZpsV8F9pg6rF72rN+v1DehBJys6NAkMlWZUpndDOthYpERkryTSy1jnE+hhP6J6L0qzwXyGn4FKR5ip7pHUaLbW2vxDdqvapccvUsvPkE9/kK8sy8SbFzJBWKQot6IbqsySNy7yuWf8476UAss=
services:
  - postgresql
before_script:
  - psql -U postgres -c "CREATE DATABASE leasetopia;"
  - export PGDATABASE=leasetopia
  - psql -U postgres -d leasetopia -a -f ./db/createdb.sql